### PR TITLE
Add [DEL], [COLOR], [SIZE], and [CENTER] tags.

### PR DESCRIPTION
**Pull request by j4nr6n**
I tested them quickly on my system.

### CODE REVIEW

**Comment by franzliedke** [comment]
Looks good.

@tobscure Did we make a decision yet on whether we wanted to support BBCode and Markdown?

**Comment by tobyzerner** [comment]
What do you mean? As in are we planning to keep BBCode as a "core extension"? Or just have one or the other enabled by default?

**Comment by franzliedke** [comment]
The latter. I vaguely remember discussing that...

**Comment by tobyzerner** [comment]
Yeah, it was in an issue somewhere... I think we concluded to only have Markdown enabled by default _once we implement the formatting buttons_.

**Comment by franzliedke** [comment]
We definitely need a way to disable some of these. _I'm looking at you, COLOR and SIZE._

**Pull request merged**
